/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.moove.projeto.moove.programas;
import br.com.bandtec.clientejira.ClienteJiraApi;
import br.com.bandtec.clientejira.modelo.Issue;
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Pichau
 */
public class ChamadoJira extends javax.swing.JFrame {

    /**
     * Creates new form ChamadoJira
     */
    public ChamadoJira() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TFtagIssue = new javax.swing.JTextField();
        TFtituloIssue = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TAdescIssue = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        jButton1.setText("Abrir Chamado");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(220, 400, 220, 23);

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(33, 230, 193));
        jLabel1.setText("Abrir Chamado");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(200, 20, 240, 40);

        jSeparator1.setForeground(new java.awt.Color(33, 230, 193));
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(60, 60, 500, 10);

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(33, 230, 193));
        jLabel2.setText("Titulo");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(120, 100, 100, 30);

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(33, 230, 193));
        jLabel3.setText("Tags");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(130, 150, 90, 40);

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(33, 230, 193));
        jLabel4.setText("Descrição");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 210, 160, 41);
        jPanel1.add(TFtagIssue);
        TFtagIssue.setBounds(220, 160, 220, 30);
        jPanel1.add(TFtituloIssue);
        TFtituloIssue.setBounds(220, 100, 220, 30);

        TAdescIssue.setColumns(20);
        TAdescIssue.setRows(5);
        jScrollPane1.setViewportView(TAdescIssue);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(220, 220, 220, 140);

        jLabel5.setForeground(new java.awt.Color(33, 230, 193));
        jLabel5.setText("(Opcional)");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(220, 190, 60, 14);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(610, 479));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String Titulo = TFtituloIssue.getText();
        String Tags = TFtagIssue.getText();
        String Desc = TAdescIssue.getText();
        
        try {
            // TODO add your handling code here:
            Gson gson = new GsonBuilder().setPrettyPrinting().create();
            
            ClienteJiraApi clienteJiraApi = new ClienteJiraApi(
                    "ericlessa.atlassian.net",
                    "eric.lessa@bandtec.com.br",
                    "RUFovWes7meK8lReAB8H1FDC"
            );
            
            
            // Exemplo de objeto para novo chamado (Issue)
            Issue novaIssue = new Issue();
            novaIssue.setProjectKey("MOOV");
            novaIssue.setSummary(Titulo);
            novaIssue.setDescription(Desc);
            novaIssue.setLabels(Tags);
            
            clienteJiraApi.criarIssue(novaIssue);
            System.out.println("Issue criada: "+gson.toJson(novaIssue));
        } catch (IOException ex) {
            Logger.getLogger(ChamadoJira.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        JOptionPane.showMessageDialog(null,
                "Chamado gerado!");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChamadoJira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChamadoJira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChamadoJira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChamadoJira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChamadoJira().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TAdescIssue;
    private javax.swing.JTextField TFtagIssue;
    private javax.swing.JTextField TFtituloIssue;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
