/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.moove.projeto.moove.programas;

import java.util.List;
import com.moove.projeto.moove.modelo.CadastroAzure;
import com.moove.projeto.moove.programas.TelaAnalista;
import br.com.bandtec.clientejira.ClienteJiraApi;
import br.com.bandtec.clientejira.modelo.Issue;
import Conexoes.ConexaoBanco;
import Conexoes.ConexaoBancoAzure;
import br.com.bandtec.clientejira.ClienteJiraApi;
import br.com.bandtec.clientejira.modelo.Issue;
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.moove.projeto.moove.modelo.DadosAPI;
import java.awt.Color;
import javax.swing.JLabel;
import org.springframework.jdbc.core.BeanPropertyRowMapper;
import org.springframework.jdbc.core.JdbcTemplate;

/**
 *
 * @author Pichau
 */
public class TelaDesenvolvedor extends javax.swing.JFrame {

    ConexaoBanco conexaoLocal = new ConexaoBanco();
    ConexaoBancoAzure conexaoAzure = new ConexaoBancoAzure();

    /**
     * Creates new form TelaDesenvolvedor
     */
    public TelaDesenvolvedor() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        List<CadastroAzure> consulta = conexaoAzure.jdbcTemplate.query
        ("select * from dbo.usuarios",
                new BeanPropertyRowMapper(CadastroAzure.class));
        for (CadastroAzure cadastroAzure : consulta) {
            if (cadastroAzure.getTipoUsuario().equals("Analista")) {
                if (jLabel7.getText().equals("Analista")) {
                    jLabel7.setText(cadastroAzure.getNome());
                } else if (jLabel8.getText().equals("Analista")) {
                    jLabel8.setText(cadastroAzure.getNome());
                } else {
                    jLabel11.setText(cadastroAzure.getNome());
                }
            }
        }
        timer1.start();
        timer1.setDelay(5);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timer1 = new org.netbeans.examples.lib.timerbean.Timer();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        LBExit = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        LBGeralAnalista3 = new javax.swing.JLabel();
        LBCPUAnalista1 = new javax.swing.JLabel();
        LBMemoriaAnalista1 = new javax.swing.JLabel();
        LBGeralAnalista2 = new javax.swing.JLabel();
        LBTempAnalista1 = new javax.swing.JLabel();
        LBsituacaoAnalista1 = new javax.swing.JLabel();
        LBcpu = new javax.swing.JLabel();
        LBTemp = new javax.swing.JLabel();
        LBmemoria = new javax.swing.JLabel();
        LBmemoria1 = new javax.swing.JLabel();
        LBcpu1 = new javax.swing.JLabel();
        LBMemoriaAnalista2 = new javax.swing.JLabel();
        LBTempAnalista2 = new javax.swing.JLabel();
        LBTemp1 = new javax.swing.JLabel();
        LBCPUAnalista2 = new javax.swing.JLabel();
        LBsituacaoAnalista2 = new javax.swing.JLabel();
        LBMemoriaAnalista3 = new javax.swing.JLabel();
        LBmemoria2 = new javax.swing.JLabel();
        LBcpu2 = new javax.swing.JLabel();
        LBCPUAnalista3 = new javax.swing.JLabel();
        LBTempAnalista3 = new javax.swing.JLabel();
        LBTemp2 = new javax.swing.JLabel();
        LBsituacaoAnalista3 = new javax.swing.JLabel();

        timer1.addTimerListener(new org.netbeans.examples.lib.timerbean.TimerListener() {
            public void onTime(java.awt.event.ActionEvent evt) {
                timer1OnTime(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Função:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(260, 10, 60, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("DEV");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(240, 40, 90, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 204));
        jLabel5.setText("|");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(230, 20, 20, 40);

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 67)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("Moove");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 0, 220, 70);

        jLabel10.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 204, 204));
        jLabel10.setText("Cadastrar");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel10);
        jLabel10.setBounds(500, 20, 97, 40);

        LBExit.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        LBExit.setForeground(new java.awt.Color(255, 0, 0));
        LBExit.setText("Exit");
        LBExit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        LBExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LBExitMouseClicked(evt);
            }
        });
        jPanel1.add(LBExit);
        LBExit.setBounds(640, 20, 60, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 204));
        jLabel6.setText("|");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(330, 20, 20, 40);

        jSeparator2.setBackground(new java.awt.Color(0, 204, 204));
        jSeparator2.setForeground(new java.awt.Color(0, 204, 204));
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(0, 70, 720, 10);

        jSeparator3.setBackground(new java.awt.Color(0, 204, 204));
        jSeparator3.setForeground(new java.awt.Color(0, 204, 204));
        jPanel1.add(jSeparator3);
        jSeparator3.setBounds(0, 200, 710, 10);

        jSeparator4.setBackground(new java.awt.Color(0, 204, 204));
        jSeparator4.setForeground(new java.awt.Color(0, 204, 204));
        jPanel1.add(jSeparator4);
        jSeparator4.setBounds(0, 350, 710, 10);

        jSeparator5.setBackground(new java.awt.Color(0, 204, 204));
        jSeparator5.setForeground(new java.awt.Color(0, 204, 204));
        jPanel1.add(jSeparator5);
        jSeparator5.setBounds(10, 490, 710, 10);

        jLabel7.setBackground(new java.awt.Color(0, 204, 204));
        jLabel7.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 204, 204));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Analista");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(0, 80, 710, 30);

        jLabel8.setBackground(new java.awt.Color(0, 204, 204));
        jLabel8.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 204, 204));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Analista");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(0, 210, 710, 30);

        jLabel11.setBackground(new java.awt.Color(0, 204, 204));
        jLabel11.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 204, 204));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Analista");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(0, 360, 710, 30);

        jLabel12.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Dashboard");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(358, 20, 130, 40);

        LBGeralAnalista3.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        LBGeralAnalista3.setForeground(new java.awt.Color(0, 204, 204));
        LBGeralAnalista3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(LBGeralAnalista3);
        LBGeralAnalista3.setBounds(180, 410, 120, 30);

        LBCPUAnalista1.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        LBCPUAnalista1.setForeground(new java.awt.Color(0, 204, 204));
        LBCPUAnalista1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(LBCPUAnalista1);
        LBCPUAnalista1.setBounds(580, 130, 110, 30);

        LBMemoriaAnalista1.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        LBMemoriaAnalista1.setForeground(new java.awt.Color(0, 204, 204));
        LBMemoriaAnalista1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(LBMemoriaAnalista1);
        LBMemoriaAnalista1.setBounds(360, 130, 100, 30);

        LBGeralAnalista2.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        LBGeralAnalista2.setForeground(new java.awt.Color(0, 204, 204));
        LBGeralAnalista2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(LBGeralAnalista2);
        LBGeralAnalista2.setBounds(180, 270, 120, 30);

        LBTempAnalista1.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        LBTempAnalista1.setForeground(new java.awt.Color(0, 204, 204));
        LBTempAnalista1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(LBTempAnalista1);
        LBTempAnalista1.setBounds(130, 130, 110, 30);

        LBsituacaoAnalista1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBsituacaoAnalista1.setText("_____________________________________");
        jPanel1.add(LBsituacaoAnalista1);
        LBsituacaoAnalista1.setBounds(220, 170, 280, 14);

        LBcpu.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        LBcpu.setForeground(new java.awt.Color(0, 204, 204));
        LBcpu.setText("CPU");
        LBcpu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(LBcpu);
        LBcpu.setBounds(520, 130, 60, 30);

        LBTemp.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        LBTemp.setForeground(new java.awt.Color(0, 204, 204));
        LBTemp.setText("Temperatura");
        LBTemp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(LBTemp);
        LBTemp.setBounds(10, 130, 120, 30);

        LBmemoria.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        LBmemoria.setForeground(new java.awt.Color(0, 204, 204));
        LBmemoria.setText("Memoria");
        LBmemoria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(LBmemoria);
        LBmemoria.setBounds(280, 130, 80, 30);

        LBmemoria1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        LBmemoria1.setForeground(new java.awt.Color(0, 204, 204));
        LBmemoria1.setText("Memoria");
        LBmemoria1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(LBmemoria1);
        LBmemoria1.setBounds(280, 260, 80, 30);

        LBcpu1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        LBcpu1.setForeground(new java.awt.Color(0, 204, 204));
        LBcpu1.setText("CPU");
        LBcpu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(LBcpu1);
        LBcpu1.setBounds(520, 260, 60, 30);

        LBMemoriaAnalista2.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        LBMemoriaAnalista2.setForeground(new java.awt.Color(0, 204, 204));
        LBMemoriaAnalista2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(LBMemoriaAnalista2);
        LBMemoriaAnalista2.setBounds(360, 260, 100, 30);

        LBTempAnalista2.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        LBTempAnalista2.setForeground(new java.awt.Color(0, 204, 204));
        LBTempAnalista2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(LBTempAnalista2);
        LBTempAnalista2.setBounds(130, 260, 110, 30);

        LBTemp1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        LBTemp1.setForeground(new java.awt.Color(0, 204, 204));
        LBTemp1.setText("Temperatura");
        LBTemp1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(LBTemp1);
        LBTemp1.setBounds(10, 260, 120, 30);

        LBCPUAnalista2.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        LBCPUAnalista2.setForeground(new java.awt.Color(0, 204, 204));
        LBCPUAnalista2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(LBCPUAnalista2);
        LBCPUAnalista2.setBounds(580, 260, 110, 30);

        LBsituacaoAnalista2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBsituacaoAnalista2.setText("_____________________________________");
        jPanel1.add(LBsituacaoAnalista2);
        LBsituacaoAnalista2.setBounds(230, 320, 280, 14);

        LBMemoriaAnalista3.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        LBMemoriaAnalista3.setForeground(new java.awt.Color(0, 204, 204));
        LBMemoriaAnalista3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(LBMemoriaAnalista3);
        LBMemoriaAnalista3.setBounds(360, 400, 100, 30);

        LBmemoria2.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        LBmemoria2.setForeground(new java.awt.Color(0, 204, 204));
        LBmemoria2.setText("Memoria");
        LBmemoria2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(LBmemoria2);
        LBmemoria2.setBounds(280, 400, 80, 30);

        LBcpu2.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        LBcpu2.setForeground(new java.awt.Color(0, 204, 204));
        LBcpu2.setText("CPU");
        LBcpu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(LBcpu2);
        LBcpu2.setBounds(520, 400, 60, 30);

        LBCPUAnalista3.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        LBCPUAnalista3.setForeground(new java.awt.Color(0, 204, 204));
        LBCPUAnalista3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(LBCPUAnalista3);
        LBCPUAnalista3.setBounds(580, 400, 110, 30);

        LBTempAnalista3.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        LBTempAnalista3.setForeground(new java.awt.Color(0, 204, 204));
        LBTempAnalista3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(LBTempAnalista3);
        LBTempAnalista3.setBounds(130, 400, 110, 30);

        LBTemp2.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        LBTemp2.setForeground(new java.awt.Color(0, 204, 204));
        LBTemp2.setText("Temperatura");
        LBTemp2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(LBTemp2);
        LBTemp2.setBounds(10, 400, 120, 30);

        LBsituacaoAnalista3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBsituacaoAnalista3.setText("_____________________________________");
        jPanel1.add(LBsituacaoAnalista3);
        LBsituacaoAnalista3.setBounds(230, 460, 280, 14);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(726, 529));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LBExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LBExitMouseClicked
        // TODO add your handling code her
        new LoginMoove().setVisible(true);
        dispose();
    }//GEN-LAST:event_LBExitMouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        new CadastroMoove().setVisible(true);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void timer1OnTime(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timer1OnTime
        // TODO add your handling code here:
        ConexaoBanco conexaoLocal = new ConexaoBanco();
        List<DadosAPI> anal1 = conexaoLocal.jdbcTemplate.query
        ("select * from ohwLeituraWind where fkmaquina = 1", 
                new BeanPropertyRowMapper(DadosAPI.class));
        for (DadosAPI dadosAPI : anal1) {
            LBCPUAnalista1.setText(dadosAPI.getCpu_load()+" %");
            LBTempAnalista1.setText(dadosAPI.getMedia_temp()+" °C");
            LBMemoriaAnalista1.setText(dadosAPI.getMemory_load()+" %");
            
            if(Double.parseDouble(dadosAPI.getCpu_load()) > 80.0 || 
               Double.parseDouble(dadosAPI.getMedia_temp()) > 80.0 ||
               Double.parseDouble(dadosAPI.getMemory_load()) > 80.0){
                
                LBsituacaoAnalista1.setForeground(Color.red);
                
            }else if(Double.parseDouble(dadosAPI.getCpu_load()) >= 30.0 && 
               Double.parseDouble(dadosAPI.getCpu_load()) <= 60.0 &&
               Double.parseDouble(dadosAPI.getMedia_temp()) >= 30.0 &&
               Double.parseDouble(dadosAPI.getMedia_temp()) <= 60.0 &&
               Double.parseDouble(dadosAPI.getMemory_load()) >= 30.0 &&
               Double.parseDouble(dadosAPI.getMemory_load()) <= 60.0){
                
                LBsituacaoAnalista1.setForeground(Color.orange);
            }else{
                LBsituacaoAnalista1.setForeground(Color.green);
            }
        }
         List<DadosAPI> anal2 = conexaoLocal.jdbcTemplate.query
        ("select * from ohwLeituraWind where fkmaquina = 2", 
                new BeanPropertyRowMapper(DadosAPI.class));
        for (DadosAPI dadosAPI : anal2) {
            LBCPUAnalista2.setText(dadosAPI.getCpu_load()+" %");
            LBTempAnalista2.setText(dadosAPI.getMedia_temp()+" °C");
            LBMemoriaAnalista2.setText(dadosAPI.getMemory_load()+" %");
            
            if(Double.parseDouble(dadosAPI.getCpu_load()) > 80.0 || 
               Double.parseDouble(dadosAPI.getMedia_temp()) > 80.0 ||
               Double.parseDouble(dadosAPI.getMemory_load()) > 80.0){
                
                LBsituacaoAnalista2.setForeground(Color.red);
                
            }else if(Double.parseDouble(dadosAPI.getCpu_load()) >= 30.0 && 
               Double.parseDouble(dadosAPI.getCpu_load()) <= 60.0 &&
               Double.parseDouble(dadosAPI.getMedia_temp()) >= 30.0 &&
               Double.parseDouble(dadosAPI.getMedia_temp()) <= 60.0 &&
               Double.parseDouble(dadosAPI.getMemory_load()) >= 30.0 &&
               Double.parseDouble(dadosAPI.getMemory_load()) <= 60.0){
                
                LBsituacaoAnalista2.setForeground(Color.orange);
            }else{
                LBsituacaoAnalista2.setForeground(Color.green);
            }
        }
        List<DadosAPI> anal3 = conexaoLocal.jdbcTemplate.query
        ("select * from ohwLeituraWind where fkmaquina = 3", 
                new BeanPropertyRowMapper(DadosAPI.class));
        for (DadosAPI dadosAPI : anal3) {
            LBCPUAnalista3.setText(dadosAPI.getCpu_load()+" %");
            LBTempAnalista3.setText(dadosAPI.getMedia_temp()+" °C");
            LBMemoriaAnalista3.setText(dadosAPI.getMemory_load()+" %");
            
            if(Double.parseDouble(dadosAPI.getCpu_load()) > 80.0 || 
               Double.parseDouble(dadosAPI.getMedia_temp()) > 80.0 ||
               Double.parseDouble(dadosAPI.getMemory_load()) > 80.0){
                
                LBsituacaoAnalista3.setForeground(Color.red);
                
            }else if(Double.parseDouble(dadosAPI.getCpu_load()) >= 30.0 && 
               Double.parseDouble(dadosAPI.getCpu_load()) <= 60.0 &&
               Double.parseDouble(dadosAPI.getMedia_temp()) >= 30.0 &&
               Double.parseDouble(dadosAPI.getMedia_temp()) <= 60.0 &&
               Double.parseDouble(dadosAPI.getMemory_load()) >= 30.0 &&
               Double.parseDouble(dadosAPI.getMemory_load()) <= 60.0){
                
                LBsituacaoAnalista3.setForeground(Color.orange);
            }else{
                LBsituacaoAnalista3.setForeground(Color.green);
            }
        }
        
    }//GEN-LAST:event_timer1OnTime

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDesenvolvedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDesenvolvedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDesenvolvedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDesenvolvedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDesenvolvedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBCPUAnalista1;
    private javax.swing.JLabel LBCPUAnalista2;
    private javax.swing.JLabel LBCPUAnalista3;
    private javax.swing.JLabel LBExit;
    private javax.swing.JLabel LBGeralAnalista2;
    private javax.swing.JLabel LBGeralAnalista3;
    private javax.swing.JLabel LBMemoriaAnalista1;
    private javax.swing.JLabel LBMemoriaAnalista2;
    private javax.swing.JLabel LBMemoriaAnalista3;
    private javax.swing.JLabel LBTemp;
    private javax.swing.JLabel LBTemp1;
    private javax.swing.JLabel LBTemp2;
    private javax.swing.JLabel LBTempAnalista1;
    private javax.swing.JLabel LBTempAnalista2;
    private javax.swing.JLabel LBTempAnalista3;
    private javax.swing.JLabel LBcpu;
    private javax.swing.JLabel LBcpu1;
    private javax.swing.JLabel LBcpu2;
    private javax.swing.JLabel LBmemoria;
    private javax.swing.JLabel LBmemoria1;
    private javax.swing.JLabel LBmemoria2;
    private javax.swing.JLabel LBsituacaoAnalista1;
    private javax.swing.JLabel LBsituacaoAnalista2;
    private javax.swing.JLabel LBsituacaoAnalista3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private org.netbeans.examples.lib.timerbean.Timer timer1;
    // End of variables declaration//GEN-END:variables
}
